version: '3.9'
services:
  database:
    container_name: database_container
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: database_user
      POSTGRES_PASSWORD: database_password
      POSTGRES_DB: bot_database
    ports:
      - '5432:5432'
  application:
    container_name: application_container
    build: ./
    image: itiszakk/telegrambot:latest
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - database